#!/bin/bash

sleep 30

while true ; do

    season=`cat season`
    curr_temp=`cat /mnt/bus.pseudo`

    relays=`./grclient.py get status | tail -1`
    cold_relay=`echo $relays | cut -d',' -f1`
    hot_relay=`echo $relays | cut -d',' -f2`

    settings=`./grclient.py get settings | tail -1`
    heatto=`echo $settings | cut -d',' -f1`
    coolto=`echo $settings | cut -d',' -f2`

    echo "current temp is $curr_temp"
    echo "cold relay is $cold_relay"
    echo "hot relay is $hot_relay"
    echo "cold set to "$coldto"
    echo "heat set to $heatto"

    if [ $cold_relay == "off" ] && [ $hot_relay == "off" ]; then
        if [ $season == "summer" ]; then
            ((curr_temp=curr_temp+1))
            echo $curr_temp > /mnt/bus.pseudo
            echo "both relays are off, it's summertime, temp is increasing..."
        else
            ((curr_temp=curr_temp-1))
            echo $curr_temp > /mnt/bus.pseudo
            echo "both relays are off, it's wintertime, temp is decreasing..."
        fi

    elif [ $cold_relay == "on" ]; then

        if [ $coolto < $curr_temp ]; then
            ((curr_temp=curr_temp-1))
            echo $curr_temp > /mnt/bus.pseudo
            echo "cold relay is on, temp is decreasing..."
        fi

    elif [ $hot_relay == "on" ]; then

        if [ $heatto > $curr_temp ]; then
            ((curr_temp=curr_temp+1))
            echo $curr_temp > /mnt/bus.pseudo
            echo "hot relay is on, temp is increasing..."
        fi

    fi

    sleep 20

done
