apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grredis
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
      containers:
      - name: grredis
        image: setilab/grredis:v1.0
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 6379
          protocol: TCP
        volumeMounts:
        - name: nfs
          mountPath: /data
