FROM python:3.5
ENV PATH=/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin
RUN pip3 install requests
WORKDIR /gr
COPY grcntrlrd.py /gr
COPY config.json /gr
COPY startup.emulator /gr/startup
CMD ["bash", "startup"]
